### ISSUE TITLE
Couple of things needed in order to build

### ISSUE THREAD

**Issue by TheMcSebi** [ytmdesktop/remote#4]
1. Package name in pubspec.yaml needs to be changed from pix_keychain to ytmdesktop_remote

2. player.dart:376 needs fixing, i assume due to a Flutter api change

3. All assets (missing images) need to be removed from pubspec.yaml and replaced by "assets/image/"

4. The following libraries are missing from pubspec.yaml
- socket_io_client: ^1.0.2
- marquee: ^2.2.0
- sliding_up_panel: ^2.0.0+1
- flutter_media_notification: ^1.2.6

I assume you accidentally copied the wrong pubspec.yaml file.
Also, what version of the media notification package were you using during development? I get frequent crashes due to it.

**Comment by TheMcSebi** [comment]
I created a pull request https://github.com/ytmdesktop/remote/pull/5 in order to address a few of these issues.

**Comment by adlerluiz** [comment]
thanks for the info, i actually uploaded the wrong file, but thanks for the corrections
